### PR TITLE
Tailwind

### PR DESCRIPTION
**Pull request by lil5**
Motive behind moving to tailwind is to decrease the bundle size of the website [Tailwind CSS vs. CSS: An in-depth comparison (speed, file size, etc.)](https://www.programonaut.com/tailwind-css-vs-css-an-in-depth-comparison-speed-file-size-etc/)

To test the waters I've tried using tailwind to style the SearchBar component https://github.com/CollActionteam/clothing-loop/pull/247#issuecomment-1160235204

### CODE REVIEW

**Comment by lil5** [comment]
**Desktop**
Screenshot 2022-06-20 at 11-52-49 The Clothing Loop Home

**Tablet**

Screenshot 2022-06-20 at 11-53-11 The Clothing Loop Home

**Mobile**

Screenshot 2022-06-20 at 11-53-30 The Clothing Loop Home

as soon as something is typed:

Screenshot 2022-06-20 at 11-58-12 The Clothing Loop Home

**Comment by timstokman** [comment]
Hey,

Did you test it?

* This change increases the bundle-size by 60kb
* Drops the lighthouse performance score by 1 point

Some other considerations:

* Was it discussed with the rest of the team? I don't particulary mind, but make sure everyone is comfortable with an extra css framework.
* You seem to have replaced only minor bits of the site with tailwind related things. Is that really worth a new css framework? I know tailwind is the new hotness now, but every new component increases the risk that in a few years you need to update dependencies, or one of your dependencies is deprecated. Esp. with frontend dependencies.

I think if we want to increase the speed of the site, we'd better start with re-encoding the images we use (looking at the lighthouse trace). We can probably save about 23MB (!!) like that.

Regarding tailwind, I'm personally not against it, but you probably need to tweak this a bit more to make sure that it actually is a positive change. Right now, it just makes things slower/more complex. Discuss it w/ the rest of the team?

**Comment by timstokman** [comment]
Don't think anyone had time to respond to that discussion yet. Maybe take that to your weekly call, or wait a bit in slack?

Regardless, I see in chrome lighthouse minor performance degradation https://deploy-preview-247--clothing-loop.netlify.app/ vs clothingloop.org. Maybe take a look at that first? Might be some stuff that's misconfigured.

**Comment by lil5** [comment]
> Regardless, I see in chrome lighthouse minor performance degradation
It does not seem to be something that can be mitigated without moving more classes to tailwind, as my assumption is that it is caused by the slight increase in bundle size. This can be done gradually while making the website responsive.

> This change increases the bundle-size by 60kb
The added tailwind classes only total to 1.7KBs

And comparing the deployment output:

#tailwind - https://app.netlify.com/sites/clothing-loop/deploys/62b04353a850a20009826601
```log
11:55:09 AM:   754.43 KB  build/static/js/2.251dc756.chunk.js
11:55:09 AM:   114.97 KB  build/static/js/mapbox-gl-csp-worker.735ad9bd.worker.js
11:55:09 AM:   49.75 KB   build/static/js/main.3c755b7f.chunk.js
11:55:09 AM:   5.42 KB    build/static/css/2.e6baa8cc.chunk.css
11:55:09 AM:   4.39 KB    build/static/css/main.5582cd96.chunk.css
11:55:09 AM:   1.64 KB    build/static/js/3.f624ca05.chunk.js
11:55:09 AM:   1.18 KB    build/static/js/runtime-main.1be108d1.js
```
#move-to-ts - https://app.netlify.com/sites/clothing-loop/deploys/62aaf04b6d20ac0008b50cae
```log
10:59:48 AM:   754.43 KB  build/static/js/2.2bbe2147.chunk.js
10:59:48 AM:   114.97 KB  build/static/js/mapbox-gl-csp-worker.735ad9bd.worker.js
10:59:48 AM:   49.61 KB   build/static/js/main.c824df8f.chunk.js
10:59:48 AM:   5.42 KB    build/static/css/2.e6baa8cc.chunk.css
10:59:48 AM:   3.96 KB    build/static/css/main.bc45461b.chunk.css
10:59:48 AM:   1.64 KB    build/static/js/3.0269d971.chunk.js
10:59:48 AM:   1.18 KB    build/static/js/runtime-main.64d1b99b.js
```

The only change I see is of around 0.4KB (gzipped I assume) from `build/static/css/main.<hash>.chunk.css`

**Pull request closed without merging**
